import Head from 'next/head';
import { useState } from 'react';
import AdultTap from '../components/AdultTap';
import Contact from '../components/Contact';
import Header from '../components/Header';
import Hero from '../components/Hero';
import Principal from '../components/Principal';
import Testimonials from '../components/Testimonials';
import Timetable from '../components/Timetable';
import ShowModal from '../components/ShowModal';

export default function Home() {
  const [showModalVisible, setShowModalVisible] = useState(true);
  return (
    <div className="relative">
      <Head>
        <title>The Chorley School of Dance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* {showModalVisible && (
        <ShowModal setShowModalVisible={setShowModalVisible} />
      )} */}
      <Hero />
      <Timetable />
      <Principal />
      <AdultTap />
      <Contact />
      <Testimonials />
    </div>
  );
}
